export interface Framework {
  id: string;
  name: string;
  category: 'Web' | 'Mobile' | 'Desktop' | 'Universal';
  outputs: string[];
}

const frameworks: Framework[] = [
  // ── Web ──
  { id: 'nextjs', name: 'Next.js', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'react', name: 'React', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'vue', name: 'Vue', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'vite', name: 'Vite', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'astro', name: 'Astro', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'nuxt', name: 'Nuxt', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'sveltekit', name: 'SvelteKit', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'angular', name: 'Angular', category: 'Web', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},

  // ── Mobile ──
  { id: 'expo', name: 'Expo', category: 'Mobile', outputs: [
    'icon.png',
    'adaptive-icon.png',
    'favicon.png',
    'splash-icon.png',
  ]},
  { id: 'react-native', name: 'React Native', category: 'Mobile', outputs: [
    'android/mipmap-mdpi/ic_launcher.png',
    'android/mipmap-hdpi/ic_launcher.png',
    'android/mipmap-xhdpi/ic_launcher.png',
    'android/mipmap-xxhdpi/ic_launcher.png',
    'android/mipmap-xxxhdpi/ic_launcher.png',
    'ios/AppIcon.appiconset/Contents.json',
    'ios/AppIcon.appiconset/icon-20.png',
    'ios/AppIcon.appiconset/icon-29.png',
    'ios/AppIcon.appiconset/icon-40.png',
    'ios/AppIcon.appiconset/icon-58.png',
    'ios/AppIcon.appiconset/icon-60.png',
    'ios/AppIcon.appiconset/icon-76.png',
    'ios/AppIcon.appiconset/icon-80.png',
    'ios/AppIcon.appiconset/icon-87.png',
    'ios/AppIcon.appiconset/icon-120.png',
    'ios/AppIcon.appiconset/icon-152.png',
    'ios/AppIcon.appiconset/icon-167.png',
    'ios/AppIcon.appiconset/icon-180.png',
    'ios/AppIcon.appiconset/icon-1024.png',
  ]},
  { id: 'flutter', name: 'Flutter', category: 'Mobile', outputs: [
    'ios/AppIcon.appiconset/Contents.json',
    'ios/AppIcon.appiconset/icon-20.png',
    'ios/AppIcon.appiconset/icon-29.png',
    'ios/AppIcon.appiconset/icon-40.png',
    'ios/AppIcon.appiconset/icon-58.png',
    'ios/AppIcon.appiconset/icon-60.png',
    'ios/AppIcon.appiconset/icon-76.png',
    'ios/AppIcon.appiconset/icon-80.png',
    'ios/AppIcon.appiconset/icon-87.png',
    'ios/AppIcon.appiconset/icon-120.png',
    'ios/AppIcon.appiconset/icon-152.png',
    'ios/AppIcon.appiconset/icon-167.png',
    'ios/AppIcon.appiconset/icon-180.png',
    'ios/AppIcon.appiconset/icon-1024.png',
    'android/mipmap-mdpi/ic_launcher.png',
    'android/mipmap-hdpi/ic_launcher.png',
    'android/mipmap-xhdpi/ic_launcher.png',
    'android/mipmap-xxhdpi/ic_launcher.png',
    'android/mipmap-xxxhdpi/ic_launcher.png',
  ]},
  { id: 'capacitor', name: 'Capacitor', category: 'Mobile', outputs: [
    'icon-only.png',
    'icon-foreground.png',
    'icon-background.png',
    'splash.png',
    'splash-dark.png',
  ]},
  { id: 'android', name: 'Android', category: 'Mobile', outputs: [
    'mipmap-mdpi/ic_launcher.png',
    'mipmap-hdpi/ic_launcher.png',
    'mipmap-xhdpi/ic_launcher.png',
    'mipmap-xxhdpi/ic_launcher.png',
    'mipmap-xxxhdpi/ic_launcher.png',
    'ic_launcher_round.png',
    'ic_launcher_foreground.png',
    'ic_launcher_background.png',
  ]},
  { id: 'ios', name: 'iOS', category: 'Mobile', outputs: [
    'AppIcon.appiconset/Contents.json',
    'icon-20.png',
    'icon-29.png',
    'icon-40.png',
    'icon-58.png',
    'icon-60.png',
    'icon-76.png',
    'icon-83.5.png',
    'icon-1024.png',
  ]},

  // ── Desktop ──
  { id: 'tauri', name: 'Tauri', category: 'Desktop', outputs: [
    '32x32.png',
    '128x128.png',
    '128x128@2x.png',
    'icon.png',
    'Square30x30Logo.png',
    'Square44x44Logo.png',
    'Square71x71Logo.png',
    'Square89x89Logo.png',
    'Square107x107Logo.png',
    'Square142x142Logo.png',
    'Square150x150Logo.png',
    'Square284x284Logo.png',
    'Square310x310Logo.png',
    'StoreLogo.png',
    'icon.icns',
    'icon.ico',
  ]},
  { id: 'electron', name: 'Electron', category: 'Desktop', outputs: [
    'icon.svg',
    'icon.png',
    'icon.icns',
    'icon.ico',
    'background.png',
    'background@2x.png',
    'icons/16x16.png',
    'icons/32x32.png',
    'icons/512x512.png',
  ]},
  { id: 'neutralino', name: 'Neutralino', category: 'Desktop', outputs: [
    'icon.png',
  ]},

  // ── Universal ──
  { id: 'pwa', name: 'PWA', category: 'Universal', outputs: [
    'favicon.ico',
    'favicon-16x16.png',
    'favicon-32x32.png',
    'apple-touch-icon.png',
    'android-chrome-192x192.png',
    'android-chrome-512x512.png',
    'site.webmanifest',
  ]},
  { id: 'windows', name: 'Windows', category: 'Universal', outputs: [
    'icon.ico',
    'Square44x44Logo.png',
    'Square150x150Logo.png',
    'StoreLogo.png',
  ]},
  { id: 'macos', name: 'macOS', category: 'Universal', outputs: [
    'icon.icns',
  ]},
  { id: 'linux', name: 'Linux', category: 'Universal', outputs: [
    'icon.png',
    '256x256.png',
    '512x512.png',
  ]},
];

export default frameworks;